export const TypeRoles = {
	cargos: [
		{ name: "Desenvolvedor Front-End" },
		{ name: "Desenvolvedor Back-End" },
		{ name: "Desenvolvedor Full Stack" },
		{ name: "Engenheiro de Software" },
		{ name: "Analista de Sistemas" },
		{ name: "Cientista de Dados" },
		{ name: "Engenheiro de Dados" },
		{ name: "Analista de Dados" },
		{ name: "Engenheiro DevOps" },
		{ name: "Administrador de Redes" },
		{ name: "Engenheiro de Redes" },
		{ name: "Analista de Segurança da Informação" },
		{ name: "Engenheiro de Segurança" },
		{ name: "Designer UX/UI" },
		{ name: "Designer Gráfico" },
		{ name: "Gerente de Projetos" },
		{ name: "Scrum Master" },
		{ name: "Product Owner" },
		{ name: "Gerente de Produto" },
		{ name: "Administrador de Sistemas" },
		{ name: "Especialista em Help Desk" },
		{ name: "Engenheiro de Suporte" },
	],
};
